### ISSUE TITLE
Error with nf start: /bin/sh: 1: pushd: not found

### ISSUE THREAD

**Issue by theteapot** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#1]
Steps to reproduce:
1. Clone repo
2. Install foreman globally
3. Install dependencies for api/ and frontend/
4. Run `nf start`

After cloning the repo, installing foreman, and installing dependencies for api/ and frontend I get the below error when running `nf start`. It seems this is because `pushd` and `popd` are commands not present in `/bin/sh` which foreman is using. 

I looked around for a way to set the default shell for foreman, but couldn't find any hints. 
However by changing my Procfile to use the following commands `nf start` didn't throw this error:
```bash
api: cd api && ./node_modules/.bin/nodemon server.js && cd ..
web: cd frontend && npm start && cd ..
```

The error from running `nf start`
```bash
[WARN] No ENV file 
23:59:21 api.1   |  /bin/sh: 1: pushd: not found
23:59:21 web.1   |  /bin/sh: 1: pushd: not found
[DONE] Killing all processes with signal  null
internal/util.js:192
  throw new errors.TypeError('ERR_UNKNOWN_SIGNAL', signal);
```
Tested on Debian 9 and Ubuntu 16.04 using both bash and zsh.

**Comment by cmoesel** [comment]
Thanks for filing this issue and providing a solution.  We do our primary development on Mac OS X systems, for which the current Procfile seems to work.  That said, there really is no reason to prefer `pushd`/`popd` over `cd`/`cd ..` in this situation, so we'll make that change.

Thanks again for the helpful and thorough report.
