### ISSUE TITLE
Add XML-formatted output to export bundles

### ISSUE THREAD

**Issue by csandersdev** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#22]
The CQL Engine does not support the JAXB-JSON format that is currently included in the ZIP export bundles. The preferred format for the CQL Engine is XML. In order to preserve existing functionality that uses the JAXB-JSON format and also support the CQL Engine, we would like the CDS AT to export both formats at the same time. See https://github.com/DBCG/cql_engine/issues/405 for the complete discussion and https://github.com/cqframework/cql-translation-service/issues/18 for the related change needed in the CQL Translation Service.

**Comment by cmoesel** [comment]
Hi @csandersdev.  I was just going through the issues and noticed I never responded to this one - but now I remember the conversation.

It looks like the support for dual output was added to the translation service, so we can look at adding that to the CDS Authoring Tool.  That support, however, was only added to the master branch -- and the AT currently exports CQL 1.3.x (off the 1.3.x branch) -- so we would likely do this during or after upgrading the CDS AT to export CQL 1.5.  We hope to do that in the next few months.

**Comment by csandersdev** [comment]
Thanks for the update @cmoesel. No urgency from my side on this. We've got a workaround in place for now.

**Comment by cmoesel** [comment]
Hi @csandersdev -- Support for XML downloads was merged in Nov 2021 ([here](https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool/commit/728aa794927dcca2c8fcf9dd2a6f020629ed5601)). I only noticed now that this issue never got closed.  Sorry about that!
