### ISSUE TITLE
no longer can connect to VSAC

### ISSUE THREAD

**Issue by alidufour** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#25]
cannot retrieve info from VSAC, same with version deployed on AHRQ site, perhaps linked to missing API key for UMLS?

**Comment by cmoesel** [comment]
Thanks for reporting this @alidufour.  It seems it must have been a temporary glitch in the VSAC API.  I just tried it now and it seems to be working.  Can you confirm it is working for you now too?

**Comment by alidufour** [comment]
yes, it seems to be intermittent
