### ISSUE TITLE
External CQL and base elements

### ISSUE THREAD

**Issue by skelt** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#45]
Hi,

I'm attempting to assign a base element to a External CQL function parameter but get the following error just after i select it from the drop down:

`×
TypeError: Cannot read property 'find' of undefined
getBaseElementName
src/components/builder/base-elements/utils.js:4
  1 | export const getBaseElementReturnType = baseElement =>
  2 |   baseElement.modifiers?.length > 0 ? baseElement.modifiers.slice(-1)[0].returnType : baseElement.returnType;
  3 | 
> 4 | export const getBaseElementName = baseElement => baseElement.fields.find(field => field.id === 'element_name').value;
  5 | 
  6 | export const getBaseElementsByType = (baseElements, type) =>
  7 |   baseElements.filter(baseElement => getBaseElementReturnType(baseElement) === type);
View compiled
onChange
src/components/builder/templates/ArgumentsTemplate.js:137
  134 | handleUpdateArgument({
  135 |   ...argumentValue,
  136 |   selected: event.target.value,
> 137 |   elementName:
      | ^  138 |     argumentValue.argSource === 'baseElement'
  139 |       ? getBaseElementName(getBaseElementById(baseElements, event.target.value))
  140 |       : getParameterById(parameters, event.target.value).name
View compiled
▶ 21 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.`

My external CQL is:

library BMICalculator
version '1'

define function BMI(height System.Quantity, weight System.Quantity):
  System.Quantity {
    value: (weight.value/(height.value*height.value)),
    unit: 'kg/m2'
  }

**Comment by cmoesel** [comment]
Thank you for reporting this.  It looks like you are running into this error running the CDS Authoring Tool locally (rather than the AHRQ-hosted version).  Is that correct?  If so, are you running on the master branch?

**Comment by skelt** [comment]
Yes running the master branch and have the latest commit.  I also deleted the mongodb and made the application create it again by running mongo cds_authoring --eval "db.dropDatabase()".  Still getting the prob.

**Comment by cmoesel** [comment]
Thanks!  We're looking into it now!

**Comment by cmoesel** [comment]
Thanks again for reporting this. We've debugged it, found the problem, and applied a fix.  We pushed the fix in commit 93dda13a62705cc1f8fa79547c6b8b1dba1eb887.  Note that some additional commits were also pushed at the same time (in case you're keeping track).

Please try pulling down the latest code to confirm that this fixes it for you.

**Comment by skelt** [comment]
Thats it working! thank you :)

**Comment by cmoesel** [comment]
Thank you for reporting this and thank you for confirming the fix!
