### ISSUE TITLE
Question about converting artifacts to FHIR STU3 and FHIR DSTU2 CQL

### ISSUE THREAD

**Issue by maxsibilla** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#7]
Hello,
I work as a researcher with the University of Pittsburgh Department of Biomedical Informatics and we have been working with this authoring tool to implement a drug-drug interaction alerting system.

I am working on the addition of Dosage in MedicationStatements and MedicationOrders as well as the comparison of dose in the frontend of the app, however, I am having some issues in converting the artifact that I create into CQL for FHIR STU3 and FHIR DSTU2. Do you have any documentation that explains the conversion process?

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/7218802/70814152-ec9a6f80-1d98-11ea-87f7-55728c714ee4.png">

Thank you for any and all help!

**Comment by cmoesel** [comment]
Hi @maxsibilla.  I apologize -- somehow I missed this issue when you filed it.  Do you still have questions about this?

The way the CDS Authoring Tool is currently designed, most of the FHIR-specific differences are actually contained in helper CQL libraries called CDS_Connect_Commons ([DSTU2](https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool/blob/master/api/data/library_helpers/CQLFiles/DSTU2/CDS_Connect_Commons_for_FHIRv102-v1.3.2.cql) / [STU3](https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool/blob/master/api/data/library_helpers/CQLFiles/STU3/CDS_Connect_Commons_for_FHIRv300-v1.0.0.cql)).  So we have specific functions (like `ActiveCondition(CondList List<Condition>)`) that contain the version-specific logic.  From the AT perspective, the library it builds just knows to call the `ActiveCondition` function -- and which CDS_Connect_Commons library is actually used (DSTU2 or STU3) depends on which version of FHIR the user exports.

There are a few cases where we need to do other stuff in Authoring Tool code (like `MedicationOrder` vs `MedicationRequest`), but those are very rare.

**Comment by maxsibilla** [comment]
Are we able to create a subpopulation of type MedicationRequest? That doesn't seem to be an option in the dropdown for subpopulation element type. To my understanding that is the STU3 equivalent of the DSTU2 MedicationOrder.

**Comment by cmoesel** [comment]
Since we try to make it so you can author an artifact once and export to multiple FHIR versions, we have to normalize on a single name per resource type.  So even though the UI _says_ `MedicationOrder`, if you export as STU3, it will in fact use the STU3 `MedicationRequest` type.

When we update to add R4 support, we will also likely refresh the UI and normalize on the R4 terms (so in the UI we will actually change `MedicationOrder` to `MedicationRequest`).

**Comment by cmoesel** [comment]
I'm closing this issue as it is over a year old and we have answered the questions.  (Also note, R4 is now supported and we did refresh the UI to use `Medication Request` rather than `Medication Order`).  If you have any further questions, feel free to open another issue.  Thanks!
