### ISSUE TITLE
Local Database Issue

### ISSUE THREAD

**Issue by cmoesel** [AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool#95]
_Originally posted by @nibaba007 in https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool/issues/72#issuecomment-1849461374_:

> What to do when encountering the following situation:
>
> ![289455695-f5068a3d-e429-4ae1-ad62-04f42cf89252-redacted2](https://github.com/AHRQ-CDS/AHRQ-CDS-Connect-Authoring-Tool/assets/2278253/0a61c3cf-c626-4b0f-9d7e-743b62abf0b5)

_Note from Admin: This issue report is related to a developer's local implementation of the CDS Authoring Tool. The AHRQ-hosted CDS Authoring Tool has not been impacted._

**Comment by jafeltra** [comment]
@nibaba007 - We’re sorry this happened to you. We cannot suggest what the proper response is to your current situation. You should work with your organization to determine the way forward.
 
To help avoid this situation in the future, we recommend implementing additional security measures, such as those outlined in [MongoDB’s Security Checklist](https://www.mongodb.com/docs/manual/administration/security-checklist/). We also recommend you regularly backup your database so you can more easily recover from situations like this. There are some possible methods documented on the [MongoDB Backup Methods documentation](https://www.mongodb.com/docs/manual/core/backups/).

**Comment by jafeltra** [comment]
Since there isn't anything we can suggest to resolve this, I'm going to close the issue.
